one master file+ one folder with other code

diff --git a/SSH-INIT-SYNC b/SSH-INIT-SYNC
--- a/SSH-INIT-SYNC
+++ b/SSH-INIT-SYNC
@@ -18,11 +18,41 @@ projectdir=$(git -C ${loc} rev-parse --show-toplevel)
 
 pushd ${loc} > /dev/null
 
-echo "projectdir is"
-echo ${projectdir}
-echo "end loc "
-projectdir=$(git -C ${loc} rev-parse --show-toplevel)
+## code 1
+if test -f "00repo_needs_initialisation00.txt" ;
+  then
+  echo "running project repository initiation (first run)"
+  sh scripts/template_init.command
+fi
 
-pushd ${loc} > /dev/null
+## code 2
+ 
+if  (test -f "03_data/001_data/README_data.md") ;
+  then
+  echo "submodules are initialised"
+  
+  else
+  echo "initialising submodules"
+  git submodule update --init --recursive
+  git submodule foreach gin init
+fi
 
-echo ${projectdir}
+## code 3
+
+
+usage() {
+    echo "$0 <sync-option>"
+    echo
+    echo "<sync-option>     The sync option defines what to do with the content of large files."
+    echo "                  It should be one of the following values:"
+    echo "                     download - Download all large file content from the server"
+    echo "                     keep     - Keep all large file content but do not download missing large files"
+    echo "                     remove   - Do not download large files and remove existing local large file content"
+    exit 1
+}
+
+# Set the variable for synchronisation option, see above 
+syncopt="remove"
+
+echo "start synchronisation in "$syncopt" mode, close window to cancel. change mode by changing the code in a text application"
+sh scripts/GIN-SYNC
